// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.wealth.techupdate.web.entity;

import com.wealth.techupdate.web.entity.Day;
import com.wealth.techupdate.web.entity.DayDataOnDemand;
import com.wealth.techupdate.web.repository.DayRepository;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect DayDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DayDataOnDemand: @Component;
    
    private Random DayDataOnDemand.rnd = new SecureRandom();
    
    private List<Day> DayDataOnDemand.data;
    
    @Autowired
    DayRepository DayDataOnDemand.dayRepository;
    
    public Day DayDataOnDemand.getNewTransientDay(int index) {
        Day obj = new Day();
        setDate(obj, index);
        setRemark(obj, index);
        return obj;
    }
    
    public void DayDataOnDemand.setDate(Day obj, int index) {
        Date date = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDate(date);
    }
    
    public void DayDataOnDemand.setRemark(Day obj, int index) {
        String remark = "remark_" + index;
        obj.setRemark(remark);
    }
    
    public Day DayDataOnDemand.getSpecificDay(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Day obj = data.get(index);
        BigInteger id = obj.getId();
        return dayRepository.findOne(id);
    }
    
    public Day DayDataOnDemand.getRandomDay() {
        init();
        Day obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return dayRepository.findOne(id);
    }
    
    public boolean DayDataOnDemand.modifyDay(Day obj) {
        return false;
    }
    
    public void DayDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = dayRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Day' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Day>();
        for (int i = 0; i < 10; i++) {
            Day obj = getNewTransientDay(i);
            try {
                dayRepository.save(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
