// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.wealth.techupdate.web.entity;

import com.wealth.techupdate.web.entity.DayIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DayIntegrationTest_Roo_Configurable {
    
    declare @type: DayIntegrationTest: @Configurable;
    
}
