// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.wealth.techupdate.web.entity;

import com.wealth.techupdate.web.entity.SpeakerDataOnDemand;
import com.wealth.techupdate.web.entity.SpeakerIntegrationTest;
import com.wealth.techupdate.web.repository.SpeakerRepository;
import java.math.BigInteger;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

privileged aspect SpeakerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SpeakerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SpeakerIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    @Autowired
    private SpeakerDataOnDemand SpeakerIntegrationTest.dod;
    
    @Autowired
    SpeakerRepository SpeakerIntegrationTest.speakerRepository;
    
    @Test
    public void SpeakerIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'Speaker' failed to initialize correctly", dod.getRandomSpeaker());
        long count = speakerRepository.count();
        Assert.assertTrue("Counter for 'Speaker' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SpeakerIntegrationTest.testFind() {
        Speaker obj = dod.getRandomSpeaker();
        Assert.assertNotNull("Data on demand for 'Speaker' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Speaker' failed to provide an identifier", id);
        obj = speakerRepository.findOne(id);
        Assert.assertNotNull("Find method for 'Speaker' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Speaker' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SpeakerIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'Speaker' failed to initialize correctly", dod.getRandomSpeaker());
        long count = speakerRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'Speaker', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Speaker> result = speakerRepository.findAll();
        Assert.assertNotNull("Find all method for 'Speaker' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Speaker' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SpeakerIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'Speaker' failed to initialize correctly", dod.getRandomSpeaker());
        long count = speakerRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Speaker> result = speakerRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'Speaker' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Speaker' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SpeakerIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'Speaker' failed to initialize correctly", dod.getRandomSpeaker());
        Speaker obj = dod.getNewTransientSpeaker(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Speaker' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Speaker' identifier to be null", obj.getId());
        speakerRepository.save(obj);
        Assert.assertNotNull("Expected 'Speaker' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SpeakerIntegrationTest.testDelete() {
        Speaker obj = dod.getRandomSpeaker();
        Assert.assertNotNull("Data on demand for 'Speaker' failed to initialize correctly", obj);
        BigInteger id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Speaker' failed to provide an identifier", id);
        obj = speakerRepository.findOne(id);
        speakerRepository.delete(obj);
        Assert.assertNull("Failed to remove 'Speaker' with identifier '" + id + "'", speakerRepository.findOne(id));
    }
    
}
