// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.wealth.techupdate.web.entity;

import com.wealth.techupdate.web.entity.Speaker;
import com.wealth.techupdate.web.entity.SpeakerDataOnDemand;
import com.wealth.techupdate.web.repository.SpeakerRepository;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect SpeakerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SpeakerDataOnDemand: @Component;
    
    private Random SpeakerDataOnDemand.rnd = new SecureRandom();
    
    private List<Speaker> SpeakerDataOnDemand.data;
    
    @Autowired
    SpeakerRepository SpeakerDataOnDemand.speakerRepository;
    
    public Speaker SpeakerDataOnDemand.getNewTransientSpeaker(int index) {
        Speaker obj = new Speaker();
        setName(obj, index);
        setProfile(obj, index);
        setProfilePicPath(obj, index);
        return obj;
    }
    
    public void SpeakerDataOnDemand.setName(Speaker obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void SpeakerDataOnDemand.setProfile(Speaker obj, int index) {
        String profile = "profile_" + index;
        obj.setProfile(profile);
    }
    
    public void SpeakerDataOnDemand.setProfilePicPath(Speaker obj, int index) {
        String profilePicPath = "profilePicPath_" + index;
        obj.setProfilePicPath(profilePicPath);
    }
    
    public Speaker SpeakerDataOnDemand.getSpecificSpeaker(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Speaker obj = data.get(index);
        BigInteger id = obj.getId();
        return speakerRepository.findOne(id);
    }
    
    public Speaker SpeakerDataOnDemand.getRandomSpeaker() {
        init();
        Speaker obj = data.get(rnd.nextInt(data.size()));
        BigInteger id = obj.getId();
        return speakerRepository.findOne(id);
    }
    
    public boolean SpeakerDataOnDemand.modifySpeaker(Speaker obj) {
        return false;
    }
    
    public void SpeakerDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = speakerRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Speaker' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Speaker>();
        for (int i = 0; i < 10; i++) {
            Speaker obj = getNewTransientSpeaker(i);
            try {
                speakerRepository.save(obj);
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            data.add(obj);
        }
    }
    
}
